services:
  publisher:
    build: ./publisher/
    networks:
      - messaging
    depends_on:
      rabbitmq:
          condition: service_healthy
  consumer:
    build: ./consumer/
    networks:
      - messaging
    depends_on:
      rabbitmq:
          condition: service_healthy
  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    networks:
      - messaging
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15672
      - 4369:4369
      - 25672:25672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3
networks:
  messaging:
    name: messaging
    driver: bridge